[Pairs]
update frequency price: 5
# seconds, how often pair prices should be updated
update frequency instruments info: 60
# seconds, how often instruments info should be updated

[Spike detector]
max range: 30
# minutes, range where spike search happens
cooldown: 60
# minutes, pair cooldown after every detection

[Chart]
timezone: UTC
# one of IANA timezones, https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
