[Contracts]
min turnover: 10M
# USD [nullable]
price update interval: 1
# seconds, how often prices should be updated
instruments info update interval: 60
# seconds, how often instruments info should be updated

[Upspike detector]
max range: 30
# minutes, range where spike search happens
max funding rate: 1
# percent per day, absolute value [float]
cooldown: 60
# minutes, contract cooldown after every detection

[Chart]
timezone: UTC
# one of IANA timezones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
