[Bot]
test mode: 0
# affects number of contracts, minimal detection threshold and other things
cloud: 0
# whether the bot is running in the cloud

[Logging]
debug: 0
format: %(asctime)s :: %(name)s :: %(levelname)s :: %(message)s
timestamp format: %m-%d %H:%M:%S
timezone: UTC
# one of IANA timezones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

[Heroku]
app name: dex-sonar
