[Bot]
test mode: 0

[Logging]
debug: 0
format: %(asctime)s :: %(name)s :: %(levelname)s :: %(message)s
timestamp format: %m-%d %H:%M:%S
timezone: UTC
# should be one of IANA timezones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
